{{- if and .Values.certificate.certManager .Values.certificate.certManager.create -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "warpstream-agent.fullname" . }}-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "warpstream-agent.labels" . | nindent 4 }}
spec:
  dnsNames: {{ toJson .Values.certificate.certManager.dnsNames }}
  issuerRef:
    {{- toYaml .Values.certificate.certManager.issuer.ref | nindent 4 }}
  secretName: {{ include "warpstream-agent.fullname" . }}-cert
{{- end }}
