{{- if .Values.pdb.create }}
apiVersion: {{ include "warpstream-agent.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "warpstream-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "warpstream-agent.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "warpstream-agent.selectorLabels" . | nindent 6 }}
{{- end }}
