{{- if .Values.scrapeConfig }}
{{- if .Values.scrapeConfig.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "warpstream-agent.secretName" . }}-hostedprometheus
  labels:
    {{- include "warpstream-agent.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
stringData:
  username: prometheus
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: {{ include "warpstream-agent.fullname" . }}
  labels:
    {{- include "warpstream-agent.labels" . | nindent 4 }}
    {{- with .Values.scrapeConfig.labels }}
    {{- tpl (toYaml . | nindent 4) $ }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  scheme: HTTPS
  scrapeInterval: {{ .Values.scrapeConfig.interval }}
  scrapeTimeout: {{ .Values.scrapeConfig.scrapeTimeout }}
  metricsPath: /api/v1/monitoring/prometheus/virtual_clusters/{{ .Values.config.virtualClusterID }}
  staticConfigs:
    - targets:
        - api.warpstream.com
  basicAuth:
    username:
      name: {{ include "warpstream-agent.secretName" . }}-hostedprometheus
      key: username
    password:
      {{ toYaml .Values.scrapeConfig.basicAuth.passwordKeyRef | nindent 6 }}
{{- end }}
{{- end }}
