{{- if .Values.config.apiKey -}}
{{- if .Values.config.agentKey -}}
{{- fail "Only one of config.apiKey or config.agentKey may be set" }}
{{- end }}
{{- if .Values.config.agentKeySecretKeyRef -}}
{{- fail "Only one of config.agentKeySecretKeyRef or config.agentKey may be set" }}
{{- end }}
{{- if .Values.config.apiKeySecretKeyRef }}
{{- fail "Only one of config.apiKey or config.apiKeySecretKeyRef may be set" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "warpstream-agent.secretName" . }}
  labels:
    {{- include "warpstream-agent.labels" . | nindent 4 }}
data:
  apikey: {{  required "A valid config.apiKey is required" .Values.config.apiKey |  b64enc }}
type: Opaque
{{- end }}
