{{- if .Values.headlessService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "warpstream-agent.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "warpstream-agent.labels" . | nindent 4 }}
  {{- with (mergeOverwrite (default (dict) .Values.annotations) (default (dict) .Values.headlessService.annotations)) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    {{- if or (.Values.config.playground) (not (hasPrefix "vci_sr_" (.Values.config.virtualClusterID | default ""))) }}
    - port: {{ .Values.service.port }}
      targetPort: kafka
      protocol: TCP
      name: kafka
    {{- end }}
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if or (.Values.config.playground) (hasPrefix "vci_sr_" (.Values.config.virtualClusterID | default "")) }}
    - port: {{ .Values.service.schemaRegistryPort | default 9094 }}
      targetPort: schema-registry
      protocol: TCP
      name: schema-registry
    {{- end }}
  selector:
    {{- include "warpstream-agent.selectorLabels" . | nindent 4 }}
{{- end }}
