{{- if .Values.producer.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "warpstream-benchmark.fullname" . }}-producer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "warpstream-benchmark.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: producer
  {{- with (mergeOverwrite (default (dict) .Values.annotations) (default (dict) .Values.service.annotations)) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - port: 8082
      targetPort: prometheus
      protocol: TCP
      name: prometheus
  selector:
    {{- include "warpstream-benchmark.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: producer
{{- end }}
