{{- if not .Values.license.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wscp.licenseSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wscp.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  license-key: {{ .Values.license.key | b64enc | quote }}
{{- end }}
