{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wscp.configSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wscp.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  config.toml: {{ .Values.config.clusterConf | b64enc | quote }}
{{- end }}
