# Secret scanning workflow.
name: Secret Scan

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  secret-scan:
    name: Secret Scan
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: '1.24.x'
          cache: false
      - name: Scan for hard-coded secrets
        run: go run ./scripts/secret_scan/main.go -files="$(git ls-files | tr '\n' ',')"
